import { SecurityDevicesRepository } from './security-devices/repositories/security-devices.repository';
import { SecurityDevicesQueryRepository } from './security-devices/repositories/security-devices.query-repository';
import { SecurityDevicesService } from './security-devices/application/security-devices.service';
import { SecurityDevicesController } from './security-devices/routers/security-devices.controller';
import { UsersRepository } from './users/repositories/users.repository';
import { UsersQueryRepository } from './users/repositories/users.query-repository';
import { UsersService } from './users/application/users.service';
import { UsersController } from './users/routers/users.controller';
import { PostsService } from './posts/application/posts.service';
import { PostsQueryRepository } from './posts/repositories/posts.query-repository';
import { PostsRepository } from './posts/repositories/posts.repository';
import { BlogsRepository } from './blogs/repositories/blogs.repository';
import { LogsRepository } from './logs/repositiories/logs.repository';
import { LogsQueryRepository } from './logs/repositiories/logs.query-repository';
import { LogsService } from './logs/application/logs.service';
import { CommentsQueryRepository } from './comments/repositories/comments.query-repository';
import { CommentsRepository } from './comments/repositories/comments.repository';
import { CommentsService } from './comments/application/comments.service';
import { BlogsQueryRepository } from './blogs/repositories/blogs.query-repository';
import { PostsController } from './posts/routers/posts.controller';
import { CommentsController } from './comments/routers/comments.controller';
import { BlogsService } from './blogs/application/blogs.service';
import { BlogsController } from './blogs/routers/blogs.controller';
import { BcryptService } from './auth/application/bcrypt.service';
import { EmailService } from './auth/application/email.service';
import { EmailManager } from './auth/application/email.manager';
import { AuthService } from './auth/application/auth.service';
import { JwtService } from './auth/application/jwt.service';
import { AuthController } from './auth/routers/auth.controller';
import { PasswordService } from './auth/application/password.service';
import { LikeRepository } from './likes/repositiories/like.repository';
import { LikeService } from './likes/application/like.service';
import { Container } from 'inversify';
import 'reflect-metadata';

export const container = new Container();

container.bind(BlogsRepository).toSelf();
container.bind(CommentsRepository).toSelf();
container.bind(LikeRepository).toSelf();
container.bind(LogsRepository).toSelf();
container.bind(PostsRepository).toSelf();
container.bind(SecurityDevicesRepository).toSelf();
container.bind(UsersRepository).toSelf();

container.bind(BlogsQueryRepository).toSelf();
container.bind(CommentsQueryRepository).toSelf();
container.bind(LogsQueryRepository).toSelf();
container.bind(PostsQueryRepository).toSelf();
container.bind(SecurityDevicesQueryRepository).toSelf();
container.bind(UsersQueryRepository).toSelf();

container.bind(BcryptService).toSelf();
container.bind(BlogsService).toSelf();
container.bind(CommentsService).toSelf();
container.bind(EmailService).toSelf();
container.bind(EmailManager).toSelf();
container.bind(JwtService).toSelf();
container.bind(LikeService).toSelf();
container.bind(LogsService).toSelf();
container.bind(PostsService).toSelf();
container.bind(SecurityDevicesService).toSelf();
container.bind(UsersService).toSelf();
container.bind(AuthService).toSelf();
container.bind(PasswordService).toSelf();

container.bind(AuthController).toSelf();
container.bind(BlogsController).toSelf();
container.bind(CommentsController).toSelf();
container.bind(PostsController).toSelf();
container.bind(SecurityDevicesController).toSelf();
container.bind(UsersController).toSelf();
